### ISSUE TITLE
add commit text, commit files changed to trigger 

### ISSUE THREAD

**Issue by shankj3** [shankj3/ocelot#49]
```yaml
trigger:
  branches:
    - master
    - dev 
  filepaths:
    - core/service1/*
  commitText:
    - buildme
```

#### concerns:
would all of these have to be true to get a build? or one of the two new ones? I.e. for the example above, how would this work for: 
- `dev`, with `core/service1/src/main/java/service.java` in the changeset 
- `dev`, with msg `changing tests [buildme]`
- `feature1`, with msg `very curious what happens here [buildme]`
- `feature2` with `core/service1/src/test/java/serviceTest.java` in changeset
