### ISSUE TITLE
Custom Notification Message

### ISSUE THREAD

**Issue by clifforous** [shankj3/ocelot#92]
Would be nice to add a custom message to a notification, maybe per event.
Something like 
```
notify:
  slack:
    channel: "#ad_ci"
    identifier: "L11"
    on:
      - event: "FAIL"
        message: "@Cliff your build failed"
```
